<?php

/**
 * @file
 * Contains ead_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * Provides help text for EAD migration module
 */
function ead_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ead_migration':
      return t('Provide Finding Aid Media XML files migration to Drupal node entities') ;
    default:
  }
}
